server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/pokedex
    username: pokedex
    password: pokedexSpringBoot

management:
  endpoints:
    web:
      exposure:
        include: '*'